language: python
branches:
  only:
  - master
  - dev
python:
  - "3.7"
  - "3.8"
  - "3.9"
install:
  - pip install pip --upgrade
  - pip install -r server/requirements.txt
script:
  - pytest server/tests
